version: 2.1

commands:
  quay_login:
    steps:
      - run:
          name: Log in to Quay
          command: docker login -u "$QUAY_USER" -p $QUAY_PASS quay.io

jobs:
  build_and_test:
    machine:
      enabled: true
      docker_layer_caching: true
    environment:
      - PARALLELISM: 4 # Input to influxdb/build.py
    parallelism: 4 # How many CircleCI test containers
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Ensure CircleCI parallelism matches "./test.sh count"
          command: "[ `./test.sh count` -eq $CIRCLE_NODE_TOTAL ]"
      - run:
          name: Execute test
          command: ./test.sh $CIRCLE_NODE_INDEX
          no_output_timeout: 1500s
      - when:
          condition:
            equal: [ 0, $CIRCLE_NODE_INDEX ]
          steps:
            - run:
                name: Rename packages
                command: |
                  set -x
                  ls build
                  mv build packages
            - store_artifacts:
                path: packages/
            - persist_to_workspace:
                root: .
                paths:
                  - packages/*.deb
  perf_test:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Start influxdb
          command: |
            debname=$(find /temp/workspace/packages/influxdb*amd64.deb)
            sudo apt install -y $debname
            sudo systemctl unmask influxdb.service
            sudo systemctl start influxdb
      - run:
          name: Run testscript
          command: |
            export CIRCLE_TEARDOWN=false
            export NGINX_HOST=localhost
            ./run_perftest.sh
workflows:
  version: 2
  on_push:
    jobs:
      - build_and_test
      - perf_test:
          requires:
            - build_and_test
